### PR TITLE
Colorscales

### PR DESCRIPTION
**Pull request by jdamiba**

### CODE REVIEW

**Comment by jdamiba** [comment]
This PR replaces https://github.com/plotly/documentation/pull/1597

**Comment by nicolaskruchten** [comment]
@Mahdis-z can you get this PR updated for inclusion into this repo? basically without the `api_create` calls and following the same pattern as the other files :)

**Comment by nicolaskruchten** [comment]
ah, doh, I see that @jdamiba has updated the PR already for the new pattern! nice job Joe!

@Mahdis-z then please review this PR to make sure it matches your intention from the previous one it replaces :)

**Comment by Mahdis-z** [comment]
> ah, doh, I see that @jdamiba has updated the PR already for the new pattern! nice job Joe!
> 
> @Mahdis-z then please review this PR to make sure it matches your intention from the previous one it replaces :)

It works perfectly +1

**Pull request merged**
